[book]
authors = ["Daniel"]
language = "en"
multilingual = false
src = "src"
title = "Notas Álgebra Lineal"

[output.html]
additional-css = ["./css/custom.css", './css/math.css']

[output.katex]

[preprocessor.katex]
renderers = ["html"]
macros = "macros.txt"
