name: mdbook deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup mdbook-katex
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-katex
          version: latest
          use-tool-cache: true
        # run: |
        #   mkdir mdbook-katex
        #   curl -sSL https://github.com/lzanini/mdbook-katex/releases/download/v0.3.2/mdbook-katex-v0.3.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook-katex
        #   echo `pwd`/mdbook-katex >> $GITHUB_PATH

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html